# This is a basic workflow to help you get started with Actions
name: Deploy Public Key
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  workflow01:
    name: Workflow Connection
    runs-on: ubuntu-latest
    steps:
      - name: Server Login
      - uses: actions/checkout@v1
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
